using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ClapSourceGenerators.SkillRegistration
{
    [Generator]
    public class SkillPackageBaseCopyGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetPackageInfo(ctx))
                .Where(info => info is not null)
                .Collect();

            context.RegisterSourceOutput(provider, GenerateSource);
        }

        private static PackageInfo? GetPackageInfo(GeneratorSyntaxContext ctx)
        {
            var classDecl = (ClassDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (symbol is not { IsAbstract: false })
                return null;

            var baseType = FindSkillPackageBase(symbol);
            if (baseType is not { TypeArguments.Length: 0 })
                return null;

            var filePath = classDecl.SyntaxTree.FilePath;

            return new PackageInfo(
                symbol.Name,
                symbol.ContainingNamespace.ToDisplayString(),
                filePath);
        }

        private static INamedTypeSymbol? FindSkillPackageBase(INamedTypeSymbol type)
        {
            var current = type.BaseType;
            while (current != null)
            {
                if (current.Name == "SkillPackageBase" &&
                    current.TypeArguments.Length == 0 &&
                    current.ContainingNamespace.ToDisplayString() == "BlacksmithCore.Infra.Profession")
                    return current;
                current = current.BaseType;
            }
            return null;
        }

        private static void GenerateSource(SourceProductionContext ctx, ImmutableArray<PackageInfo?> infos)
        {
            // Merge by (Namespace, ClassName) — handle multiple partial declarations.
            // When a class is split across multiple .cs files, each partial yields
            // an identical PackageInfo; dedup by class key to avoid duplicate AddSource.
            var seen = new HashSet<string>();
            foreach (var info in infos)
            {
                if (info == null)
                    continue;

                var classKey = $"{info.Namespace}.{info.ClassName}";
                if (!seen.Add(classKey))
                    continue;

                ctx.AddSource(
                    $"{info.Namespace}.{info.ClassName}.Copy.g.cs",
                    GeneratePartialClass(info));
            }
        }

        private static string GeneratePartialClass(PackageInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using BlacksmithCore.Infra.Profession;");
            sb.AppendLine();
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
            sb.AppendLine($"partial class {info.ClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public override SkillPackageBase Copy()");
            sb.AppendLine("    {");
            sb.AppendLine($"        {info.ClassName} copy = new();");
            sb.AppendLine($"        copy._availableSkillNames = new(_availableSkillNames);");
            sb.AppendLine($"        return copy;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
        internal sealed class PackageInfo
        {
            public string ClassName { get; }
            public string Namespace { get; }
            public string FilePath { get; }

            public PackageInfo(string className, string @namespace, string filePath)
            {
                ClassName = className;
                Namespace = @namespace;
                FilePath = filePath;
            }
        }
    }
}